image: publysher/hugo

before_script:
  - git submodule
  - git submodule update

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
  
test:
  script:
  - hugo
  except:
  - master
