baseurl = "https://developers.eyeson.team/api/"
languageCode = "en-us"
title = "eyeson API documentation"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "VisoCon GmbH"
	description = "eyeson API documentation"
	copyright = "VisoCon GmbH"

	# Repository
	# provider = "GitHub"
	# repo_url = "https://github.com/visocon/api-doc"

	version = "1.0.0"
	logo = "images/logo.svg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "deep-purple"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = "eyeson_team"
	github  = "visocon"
	email   = ""


[[menu.main]]
	name   = "eyeson API"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "API Reference"
	url    = "api-reference/"
	weight = 20

[[menu.main]]
	name   = "Websocket Events"
	url    = "websocket-events/"
	weight = 30

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
